
version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    links:
      - "db:db"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@soul.it
      - PGADMIN_DEFAULT_PASSWORD=admin
  confluence:
    image: confluence-server:7.15.1
    build:
      context: .
    #image: atlassian/confluence-server:7.15.1
    container_name: confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      ##################################################
      # define CONFLUENCE_FOLDER in local .env file
      # Es.
      # CONFLUENCE_FOLDER=/Users/bsorrentino/confluence
      #
      ##################################################
      - $CONFLUENCE_FOLDER:/var/atlassian/application-data/confluence
    links:
      - "db:db"
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 5000
        hard: 5000
    environment:
      - JVM_MINIMUM_MEMORY=4096m
      - JVM_MAXIMUM_MEMORY=4096m
volumes:
    pgdata: {}
